server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: /opt/pragatix/access-logs
      prefix: access_log
      suffix: .log
      file-date-format: .yyyy-MM-dd
      pattern: '%h %l %u %t "%r" %s %b %D'
      rotate: true
      max-days: 7
spring:
  application:
    name: spdms-backend
  datasource:
    url: ${DB_URL}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  security:
    user:
      name: admin
      password: admin
jwt:
  secret: spdms_super_secret_key_must_be_at_least_256_bits_long_for_hs256_algorithm
  expiration: 57600000
  student-expiration: 57600000
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://pragatix.in,https://www.pragatix.in}
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
    path: /api/api-docs
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}
    path: /api/swagger-ui.html
    tags-sorter: alpha
logging:
  level:
    com.spdms: DEBUG
    org.springframework.security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when-authorized
  health:
    db:
      enabled: true
      enabled: true
zepto:
  mail:
    url: https://api.zeptomail.in/v1.1/email
    token: ${ZEPTO_MAIL_TOKEN:Zoho-enczapikey PHtE6r1bRb3ojDYpoUAFtPGwRcOiZN8o++hheANCtYYUCPVQHk1R/9svlDS3qBwtUfNAHabPyt1vsbiY5emFJ2e7Nm9LCmqyqK3sx/VYSPOZsbq6x00fuVwZf0HVUoDpdNRu1ybevN7dNA==}
    template-key: 2518b.27e5cd5171e7cdd6.k1.3c2208d0-9356-11f1-8e34-d2cf08f4ca8c.19fe29d81dd
    sender-address: noreply@pragatix.in
    sender-name: Pragatix