server:
  address: 0.0.0.0
  port: 8080
spring:
  application:
    name: pragatix-backend
  main:
    banner-mode: "off"
    log-startup-info: false
  datasource:
    url: jdbc:mysql://localhost:3307/pragatix?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: sharu
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: admin
      password: admin
jwt:
  secret: spdms_super_secret_key_must_be_at_least_256_bits_long_for_hs256_algorithm
  expiration: 57600000
  student-expiration: 57600000
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
logging:
  level:
    root: WARN
    jjcet.PragatiX: INFO
    org.springframework: WARN
    org.springframework.security: ERROR
    org.hibernate: WARN
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    com.zaxxer.hikari: WARN
zepto:
  mail:
    url: https://api.zeptomail.in/v1.1/email
    token: ${ZEPTO_MAIL_TOKEN:Zoho-enczapikey PHtE6r1bRb3ojDYpoUAFtPGwRcOiZN8o++hheANCtYYUCPVQHk1R/9svlDS3qBwtUfNAHabPyt1vsbiY5emFJ2e7Nm9LCmqyqK3sx/VYSPOZsbq6x00fuVwZf0HVUoDpdNRu1ybevN7dNA==}
    template-key: 2518b.27e5cd5171e7cdd6.k1.3c2208d0-9356-11f1-8e34-d2cf08f4ca8c.19fe29d81dd
    sender-address: noreply@pragatix.in
    sender-name: Pragatix