server:
  port: 8080

spring:
  application:
    name: spdms-backend

  datasource:
    url: jdbc:mysql://localhost:3307/spdms_lab?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: sharu
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  security:
    user:
      name: admin
      password: admin

jwt:
  secret: spdms_super_secret_key_must_be_at_least_256_bits_long_for_hs256_algorithm
  expiration: 86400000
  student-expiration: 43200000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha

logging:
  level:
    com.spdms: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG